name: Deploy Laravel ke Hosting

on:
  push:
    branches:
      - main # Pipeline berjalan saat ada push ke branch main

jobs:
  web-deploy:
    runs-on: self-hosted
    timeout-minutes: 7200 # for 5 days
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: 🐘 Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Sesuaikan dengan versi PHP di hosting Anda
        
    - name: 📦 Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
      
    - name: 🛠️ Setup Node.js (Jika menggunakan Vite/Mix)
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        
    - name: 🏗️ NPM Install and Build
      run: |
        npm install
        npm run build
        
    - name: 🚀 Sync Core Laravel Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home/notiontr/kapabelindonesia/
        exclude: '["**/.git*", "**/.git*/**", "**/node_modules/**", "tests/**", ".env.example", "public/**"]'

    - name: 🌐 Sync Public Folder to Public HTML
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
        server-dir: /home/notiontr/public_html/kapabelindonesia.com/